isomerpages/iras-taxacademy

_seminars-and-conferences/1-upcoming.md

Added text " I am Bernard" in the site

---

_who-we-are/7-trainers.md

Removed "**" and added a "." on trainers page

Updated Trainers page

---

.travis.yml
_executive-tax-programmes/3-income-tax.md
netlify.toml
package-lock.json
package.json

Close registration for ETP L1 (Income Tax) Intake 1/2019.

Update to Income Tax page

---

_executive-tax-programmes/5-International Tax Programmes.md

For all progs - Updated registration will open six weeks before course commencement

Updated Registration Details

---

_executive-tax-programmes/1-tax-training-roadmap.md
_executive-tax-programmes/3-income-tax.md
_executive-tax-programmes/4-goods-and-services-tax.md
_executive-tax-programmes/5-International Tax Programmes.md
_executive-tax-programmes/6-customised-programmes.md
_tomorrow-tax-professional/2-book-prizes.md
_tomorrow-tax-professional/5-going-places-in-tax.md
_who-we-are/7-trainers.md

Updated all structured tax training programme pages as suggested and also removed the vertical line from the pages.

Updated Structured Tax Training Programmes

---

_executive-tax-programmes/4-goods-and-services-tax.md

Close registration for ETP Level 2 GST

Close Registration for GST level 2

---

_data/homepage.yml
index.md

Website Announcement

---

index.md

further edited on announcement. thanks!

Adding another new line

---

_data/contact-us.yml
_data/homepage.yml
index.md

Update on TA Homepage

---

_executive-tax-programmes/4-goods-and-services-tax.md

Close Registration for Level 2 GST

Close Registration for Level 2 GST

---

_executive-tax-programmes/5-International Tax Programmes.md

Update Closing Date for WU Programme Registrations

Update Closing Date for WU Programme Registrations

---

_executive-tax-programmes/5-International Tax Programmes.md

Update registration date for WU-TA Adv TP Programme

Update 5-International Tax Programmes.md

---

_executive-tax-programmes/5-International Tax Programmes.md
_who-we-are/3-curriculum-and-exam-development-committee.md

Updated CED Members and Close Registration for WU Prog

Updated CED and Close Registration for WU Prog

---

index.md

Updated Homepage Banner on Opening Hours

Updated Homepage Banner on Opening Hours

---

_executive-tax-programmes/4-goods-and-services-tax.md
index.md
pages/contact-us.md

Closed Level 1 & 2 GST Registration and Updated Tax Book Homepage

Closed Level 1 & 2 GST Registration and Updated Tax Book Homepage

---

index.md

Updated Tax Book Homepage

---

_executive-tax-programmes/2-programme-calendar.md

Update Programme Calendar

---

_executive-tax-programmes/income-tax.md

Update file: income-tax.md

---

_executive-tax-programmes/goods-and-services-tax.md

moved statament to top of page

Update Level 2 GST hyperlinked statement

---

_executive-tax-programmes/goods-and-services-tax.md
_executive-tax-programmes/income-tax.md
_executive-tax-programmes/international-tax.md

Add planning to Adv Int Tax Planning under discount and change next class of L2 IT to Nov 2021

Add planning to Adv Int Tax Planning under discount and change next class of L2 IT to Nov 2021

---

_who-we-are/board-of-directors.md

Update file: board-of-directors.md

---

_executive-tax-programmes/goods-and-services-tax.md

Hi Eunice, 2nd attempt to close GST L1 2/2021 registration

2nd attempt to close GST L1 2/2021 Registration

---

_who-we-are/curriculum-and-examination-development-committee.md

Hi Eunice, I have updated TA Website on CED page as per request.
Thank you.

Update file: curriculum-and-examination-development-committee.md

---

_executive-tax-programmes/international-tax.md

Close registration for Level II International Tax 1/2021

Update file: international-tax.md

---

_executive-tax-programmes/international-tax.md

Hi Eunice,
I have closed the registration for the above 2 programmes.
For your review pls.
Thanks!
Regards,
Anna

Update TA Website: Adv TT (2021) and Adv ITP (2021) 

---

_executive-tax-programmes/goods-and-services-tax.md

update for Level 1 & 2 GST programmes

Update file: goods-and-services-tax.md

---

_structured-tax-training/income-tax.md

Hi Eunice,
This pull request is to close ATP (18) full programme reg.  Sher-Lin approval has been sought.    
Thanks.
Anna

To Update Level 3 ATP: ATP(18) close registration (Full programme)

---

_structured-tax-training/goods-and-services-tax.md
_structured-tax-training/international-tax.md

Remove the paragraph that mentions 10% discount for courses under GST and International Tax pages.

Structured Tax Training

---

_seminars-and-conferences/upcoming-seminars-and-conferences.md
_structured-tax-training/income-tax.md

To close registration for L2 Income Tax 2/2022

To close registration for L2 Income Tax 2/2022

---

_structured-tax-training/income-tax.md
_structured-tax-training/international-tax.md

Hi Eunice,  for pull request approval.  Thanks.

Edit WU-TA Oct Dates and ATP 1-2023 update Reg to Closed

---

_structured-tax-training/income-tax.md
_structured-tax-training/programme-calendar.md
_structured-tax-training/tax-training-roadmap.md

Hi Eunice,  
Can approve again ler : )

Edit TA Prog Calendar for WU-TA and Edit ATP 1-2023 to remove 'now'

---

_seminars-and-conferences/upcoming-seminars-and-conferences.md

…ame":"upcoming-seminars-and-conferences.md","userId":"102"}

Edit Typo - 24 July

---

_structured-tax-training/income-tax.md

close registration for Level 2 income tax

---

_who-we-are/board-of-directors.md

…directors.md","userId":"166"}

Update file: board-of-directors

---

_who-we-are/board-of-directors.md

…directors.md","userId":"102"}

Update Ajay Designation

---

_who-we-are/board-of-directors.md

…directors.md","userId":"166"}

Update new BMs CVs and YF designation

---

_structured-tax-training/Other Tax Related Programmes.md

Update other tax programmes

---

_who-we-are/curriculum-and-examination-development-committee.md

Updated CED members as per email request.

Update of CED Members

---

_structured-tax-training/income-tax.md

update to interest form statement

---

_structured-tax-training/terms-and-conditions.md

can u check it out and let mw know what has been sent you?

testing to edit
